### ISSUE TITLE
Build Failing with Latest Gemmi

### ISSUE THREAD

**Issue by kmdalton** [Hekstra-Lab/reciprocalspaceship#1]
I am not sure why yet, but the rs build fails with gemmi 0.4.0 which is the latest in pypi. For the time being, I have just made gemmi 0.3.8 the required version in setup.py.

**Comment by wojdyr** [comment]
Oops, I didn't include some files in MANIFEST.in and they are not in the PyPI package. I'll fix it today.

**Comment by wojdyr** [comment]
I just uploaded gemmi-0.4.0.post1 to PyPI, hopefully all will work now

**Comment by kmdalton** [comment]
awesome! i will test and resolve this issue.

**Comment by kmdalton** [comment]
Looks good. Thanks for the help, @wojdyr.
