### ISSUE TITLE
broken URL

### ISSUE THREAD

**Issue by DHekstra** [Hekstra-Lab/reciprocalspaceship#141]
the link referring to 
http://legacy.ccp4.ac.uk/html/mtzformat.html#coltypes

at https://hekstra-lab.github.io/reciprocalspaceship/api/autoapi/reciprocalspaceship.summarize_mtz_dtypes.html

does no longer work and should read instead:
https://www.ccp4.ac.uk/html/mtzformat.html#coltypes (the #coltypes part does not actually work)

**Comment by JBGreisman** [comment]
https://www.ccp4.ac.uk/html/mtzformat.html#column-types is the URL this should be updated to
