### ISSUE TITLE
Converting Structure Factors to Intensities

### ISSUE THREAD

**Issue by kmdalton** [Hekstra-Lab/reciprocalspaceship#148]
We have made it easy to convert intensities to structure factors using our French-Wilson implementation. However, sometimes I find myself wanting to go the other direction. This is especially useful in comparing `careless` output to other methods. 

I propose we provide a method for doing this conversion which takes into account uncertainties. By this I mean,

1) From the definition of variance, `I = SigF*SigF + F*F`
2) From uncertainty propation, `SigI = abs(2*F*SigF)`

Note that 2 is only approximate, we could do better if we knew the distribution of F. For starters, we could just add this as a function in the algorithms submodule.

**Comment by dennisbrookner** [comment]
Does it seem prudent to give these columns a name that explicitly describes what has been done? Just so as to a) not overwrite existing columns and b) avoid confusion/misinterpretation. Call it like, `I_backcalc` or `I_fromF` or something snappier and equally informative.

**Comment by JBGreisman** [comment]
to avoid that issue,  I think we could use an API that returns a new DataSet object (similar to what we do for `rs.algorithms.scale_merged_intensities()`.

**Comment by dennisbrookner** [comment]
@kmdalton Could you point me towards a suitable dataset for testing that contains `F`/`SigF` columns, or even better, contains `F`/`SigF` and also `I`/`SigI` two which they could be compared?

**Comment by dennisbrookner** [comment]
You could send it to me offline, or put I suppose just put it in the `tests/data` directory on the `intensities-clean` branch

**Comment by kmdalton** [comment]
i believe [this file](https://github.com/Hekstra-Lab/reciprocalspaceship/blob/main/tests/data/algorithms/phenix_fw_ref.mtz) in `tests/data/algorithms` fits the bill. As per [tests/algorithms/conftest.py](https://github.com/Hekstra-Lab/reciprocalspaceship/blob/6d536faf129013fa3a4233553852a3f931786b30/tests/algorithms/conftest.py#L44), it should be available to tests in `tests/algorithms` namespace under the `fixture`: `ref_hewl`. 

Let me know if that works for you.

**Comment by dennisbrookner** [comment]
Ah amazing, thanks!
