### ISSUE TITLE
support ccp4 convention in add_rfree function

### ISSUE THREAD

**Issue by minhuanli** [Hekstra-Lab/reciprocalspaceship#154]
It seems useful to make `rs.utils.add_rfree` function also support ccp4 convention rfree flags.

Can add a boolean argument named `ccp4_convention` default False. When set to True, change the column name to `FreeR_flag` and convert value `0` to be test set.

**Comment by minhuanli** [comment]
Is there any specific issue should be considered with this new tiny extension? If not, I am happy to make this happen and create a PR.

**Comment by JBGreisman** [comment]
I think that this seems reasonable, but I will need to look into it a bit to see if there are any gotchas here. I think your suggestion all sounds worthwhile though to ensure we support both CCP4/Phenix formats.

**Comment by minhuanli** [comment]
Related PR has been opened, once reviewed and merged, this issue can be closed.
