### ISSUE TITLE
`rs.utils.copy_rfree()` should take `rfree_key` argument

### ISSUE THREAD

**Issue by dennisbrookner** [Hekstra-Lab/reciprocalspaceship#159]
I just ran into a situation where I had to manually rename columns before using `rs.utils.copy_rfree()`, because the function does not accept a custom column name. I think this call should become:
```python
copy_rfree(dataset, dataset_with_rfree, rfree_key="R-free-flags", inplace=False)
```
`"R-free-flags"`, the Phenix naming convention, is a sensible default value for `rfree_key`.

I feel similarly, though less strongly, that `rs.utils.add_rfree()` should also accept the `rfree_key` argument. I think this is relevant to the changes proposed in #154; I'm raising this as a separate issue because it is a quicker fix that I can tackle first.

**Comment by JBGreisman** [comment]
Yep -- this proposed change seems reasonable to me.
