### ISSUE TITLE
Add Anomalous Flag to DataSet.hkl_to_asu

### ISSUE THREAD

**Issue by kmdalton** [Hekstra-Lab/reciprocalspaceship#16]
Right now it is sort of frustrating to map reflections to the reciprocal asu while preserving their sign.
The cleanest solution I've come up with so far is this: 
 
```python
ds = rs.read_mtz(inFN).hkl_to_asu()
fplus = ds['M/ISYM']%2 == 1 #Identify friedel plus reflections
ds = ds[~fplus].apply_symop('-x,-y,-z').append(ds[fplus])
```
The problem with just letting this be the supported approach is that it requires the user to have to understand the `M/ISYM` column. Given that `M/ISYM` is really sort of an odd historical artifact more than anything, I  think we should provide an intuitive method to solve this. I propose we embed a solution like this within `DataSet.hkl_to_asu` in the form of a a new named parameter `anomalous` which defaults to false.

**Comment by JBGreisman** [comment]
Yep -- I agree that limiting the required knowledge regarding `M/ISYM` is advantageous. I'm in favor of some sort of `anomalous` flag that can be given to functions to alter the behavior for Friedels -- to my recollection `cctbx` does some similar things. 

I think it may be preferable to limit this sort of behavior to raise an exception for merged datasets. In my mind the preferred way to store anomalous data for a merged dataset is in a two-column format stored at the plus-Friedel Miller index. In that case, `DataSet.stack_anomalous()` can be used to remap Friedels to the +/- ASU.
