### ISSUE TITLE
_cache_index_dtypes reads like a method name

### ISSUE THREAD

**Issue by kmdalton** [Hekstra-Lab/reciprocalspaceship#22]
I have to fight really hard to prevent my brain from parsing `_cache_index_dtypes` as a method name. That is I interpret `cache` as a verb. This is low priority, but could we switch this attribute name to `_index_dtypes_cache`?

**Comment by JBGreisman** [comment]
I think that this seems reasonable. I think consistently naming attributes as "nouns" and methods as "verbs" seems like a good decision -- even if they are considered private.
