### ISSUE TITLE
broken URL

### ISSUE THREAD

**Issue by DHekstra** [Hekstra-Lab/reciprocalspaceship#53]
the link to https://www.ccp4.ac.uk/html/mtzformat.html#coltypes

on https://hekstra-lab.github.io/reciprocalspaceship/api/autoapi/reciprocalspaceship.summarize_mtz_dtypes.html#reciprocalspaceship.summarize_mtz_dtypes

is broken (at the moment)

**Comment by wojdyr** [comment]
it was moved: www.* -> legacy.*
But I also see that https doesn't work well at the moment (http works).

**Comment by JBGreisman** [comment]
Thanks for the heads up -- I can change that hyperlink to point to http://legacy.ccp4.ac.uk/html/mtzformat.html#coltypes for the time being.
