### ISSUE TITLE
keeping track of parent spacegroup symop?

### ISSUE THREAD

**Issue by DHekstra** [Hekstra-Lab/reciprocalspaceship#69]
For EF-X experiments in which ON and OFF data are merged in a lower-symmetry and higher symmetry spacegroup for perturbed and unperturbed data sets, respectively, it might be helpful to retain, in some way, the symops that map the lower-sym datasets ASU to the parent ASU, or to otherwise facilitate this mapping by comparing two settings.

**Comment by JBGreisman** [comment]
I'm not sure I fully understand this request. In general for such a situation it seems that one would have two `DataSet` objects (one for ON, one for OFF), and that they would have different spacegroup attributes. In that case, it is possible to use the symmetry operations of the higher symmetry `DataSet.spacegroup` to do such comparisons for the lower symmetry `DataSet`. 

If you had something more specific in mind -- please provide some more details / a more specific example so I can better help.

**Comment by DHekstra** [comment]
I had a situation in which I wanted to expand a OFF P21 21 21 data set to compare per reflection to the ON P21 1 1 data. I was not sure which sym op would give me the corresponding set of OFF P21 1 1 reflections (I figured it out, but it might be nice to have this stored somewhere).

**Comment by JBGreisman** [comment]
As we discussed offline, this may be possible to automate, but is tricky to get correct in the general case. I think the best solution for now is to have this be on the user to keep track of. 

I also think this analysis is pretty particular to EFX, so a solution to this may be better suited to live outside of `rs`
