### ISSUE TITLE
Generalize method for assigning reflections to resolution bins

### ISSUE THREAD

**Issue by JBGreisman** [Hekstra-Lab/reciprocalspaceship#9]
It is common to assign reflections to resolution bins for different types of crystallographic analyses. This functionality is used in `rs.utils.add_rfree()`, as well as in `rs.algorithms.scale_merged_intensities()` when average intensities are computed isotropically. 

Since this is a common operation for computing crystallographic stats, I think this functionality should be refactored to be a built-in method for `DataSet` -- something like `DataSet.assign_resolution_bins(nbins=20)`.

**Comment by kmdalton** [comment]
@JBGreisman, are you planning to have an equal number of reflections per bin? Or are you planning to evenly space in `dHKL**-2`? My vote for a default behavior is to make the bins equal in reflection count.

**Comment by JBGreisman** [comment]
I agree -- I prefer having equal number of reflections as the default behavior so that by-bin statistics are as directly comparable as possible.
